CREATE DATABASE productandcategory;

use productandcategory;

CREATE TABLE `Category` (
   ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL
);

CREATE TABLE `Product` (
  `PRODUCT_ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `PRODUCT_NAME` VARCHAR(255) NOT NULL,
  `CATEGORY_ID` INT,
    FOREIGN KEY (`CATEGORY_ID`) REFERENCES `Category` (`ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ;










